vol_profile_homepage:
    path:     /hello/{name}
    defaults: { _controller: VolProfileBundle:Default:index }
vol_profile_index:
    path:     /profile
    defaults: {_controller: VolProfileBundle:VolProfile:index }
