vol_profile_homepage:
    path:     /hello/{name}
    defaults: { _controller: VolProfileBundle:Default:index }
    
vol_profile_show:
    path:     /show
    defaults: {_controller: VolProfileBundle:VolProfile:show }
    
vol_profile_notification:
    path:     /{email}/notification
    defaults: {_controller: VolProfileBundle:Notification:notification }