vol_profile:
    resource: "@VolProfileBundle/Resources/config/routing.yml"
    prefix:   /

athwela_entity:
    resource: "@AthwelaEntityBundle/Resources/config/routing.xml"
    prefix:   /

athwela_profile_settings_user:
    resource: "@AthwelaProfileSettingsUserBundle/Resources/config/routing.yml"
    prefix:   /profile-settings

athwelalogin_user:
    resource: "@AthwelaloginUserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"


fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

#fos_user_resetting:
#    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
#    prefix: /resetting
#
fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profileSettings
