services:
#    athwelalogin_user.example:
#        class: Athwela\login\UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    athwela_login_user.registration.form.type:
        class: Athwela\login\UserBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: athwela_user_registration }