athwela_administrator_admin:
    path:     /admin
    defaults: { _controller: AthwelaAdministratorBundle:Default:Admin }
    
athwela_administrator_message:
    path:     /message
    defaults: { _controller: AthwelaAdministratorBundle:Default:Messages }

athwela_administrator_project:
    path:     /project
    defaults: { _controller: AthwelaAdministratorBundle:Default:Project }
    
athwela_administrator_adminDash:
    path:     /adminDash
    defaults: { _controller: AthwelaAdministratorBundle:Approvals:adminDash }
    
athwela_administrator_adminSet:
    path:     /adminSettings
    defaults: { _controller: AthwelaAdministratorBundle:Default:adminSettings }    
    
#-------------------------------volunteer admin routes-------------------------------------------#    
athwela_administrator_volunteer:
    path:     /volunteer
    defaults: { _controller: AthwelaAdministratorBundle:Approvals:adminVols }

athwela_administrator_reject:
    path:     /adminReject/{email}
    defaults: { _controller: AthwelaAdministratorBundle:Approvals:rejectVols }

athwela_administrator_approve:
    path:     /adminApprove/{email}
    defaults: { _controller: AthwelaAdministratorBundle:Approvals:approveVols }

athwela_administrator_search:
    path:     /adminApprove/
    defaults: { _controller: AthwelaAdministratorBundle:Approvals:searchVol }
#--------------------------------------------------------------------------------------------------#

#------------------------------routing relavent to organization------------------------------------#

athwela_administrator_organization:
    path:     /organization
    defaults: { _controller: AthwelaAdministratorBundle:ApprovalsOrg:adminOrg }
athwela_administrator_Orgapprove:
    path:     /adminApprove/
    defaults: { _controller: AthwelaAdministratorBundle:ApprovalsOrg:approveOrgs }
athwela_administrator_Orgreject:
    path:     /adminApprove/
    defaults: { _controller: AthwelaAdministratorBundle:ApprovalsOrg:rejectOrgs }
athwela_administrator_Orgsearch:
    path:     /adminApprove/
    defaults: { _controller: AthwelaAdministratorBundle:ApprovalsOrg:searchOrg }
    
#---------------------------------------------------------------------------------------------------#
