services:
#    athwela_profile_settings_user.example:
#        class: Athwela\ProfileSettings\UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

#    athwela_login_user_password.registration.form.type:
#        class: Athwela\ProfileSettings\UserBundle\Form\Type\ChangePasswordFormType
#        tags:
#            - { name: form.type, alias: athwela_profile_setting_change_password }
