org_profile_homepage:
    path:     /hello/{name}
    defaults: { _controller: OrgProfileBundle:Default:index }
org_profile_show:
    path:     /{id}/show
    defaults: {_controller: OrgProfileBundle:OrgProfile:show }
org_profile_notification:
    path:     /{id}/notification
    defaults: {_controller: OrgProfileBundle:OrgProfile:notification }