show_project:
    path:   /show/{ID}
    defaults: {_controller: AthwelaProjectBundle:Project:showProject }
    
Athwela_projectProfile_settings:
    path:   /render
    defaults: {_controller: AthwelaProjectBundle:Settings:create }
