athwela_project_homepage:
    path:     /
    defaults: { _controller: AthwelaProjectBundle:Default:index }

show_project:
    path:     /{ID}
    defaults: { _controller: AthwelaProjectBundle:Project:showProject }
